accs = {
    1:'Applied',
    0:'Not Applied'
}

cos = {
    1:'Applied',
    0:'Not Applied'
}

citz = {
    20: "Cuba",
21: "Argentina",
22: "Bahamas",
23: "Belize",
24: "Bolivia",
25: "Canada",
26: "Chile",
27: "China",
28: "Colombia",
29: "Cuba",
30: "Dominican Republic",
31: "Ecuador",
32: "El Salvador",
33: "France",
34: "Germany",
35: "Ghana",
36: "Gr Brit/UK/England",
37: "Guatemala",
38: "Guyana",
39: "Haiti",
40: "Honduras",
41: "India",
42: "Iran",
43: "Israel",
44: "Italy",
45: "Jamaica",
46: "Jordan",
47: "Korea (North/South)",
48: "Lebanon",
49: "Mexico",
50: "Nicaragua",
51: "Nigeria",
52: "Pakistan",
53: "Panama",
54: "Peru",
55: "Philippines",
56: "USSR/Russ/Rep Sov St",
57: "Thailand",
58: "Trinidad and Tobago",
59: "Venezuela",
60: "Vietnam(North/South)",
61: "Afghanistan",
62: "Albania",
63: "Antigua and Barbuda",
64: "Australia",
65: "Bangladesh",
66: "Barbados",
67: "Benin",
68: "Brazil",
69: "Costa Rica",
70: "Greece",
71: "Guinea",
72: "Hong Kong",
73: "Indonesia",
74: "Iraq",
75: "Ireland",
76: "Kuwait",
77: "OTHER country code",
78: "Laos",
79: "Liberia",
80: "Malaysia",
81: "Netherlands",
82: "Poland",
83: "Romania",
84: "Portugal",
85: "Spain",
86: "St. Kitts",
87: "Syria",
88: "Taiwan",
89: "Togo",
90: "Yemen",
91: "Yugoslavia",
100: "Algeria",
101: "Andorra",
102: "Angola",
103: "Armenia",
104: "Austria",
105: "Azerbaijan",
106: "Bahrain",
107: "Belarus",
108: "Belgium",
109: "Bhutan",
110: "Bosnia & Herzegovina",
111: "Botswana",
112: "Brunei Darussalem",
113: "Bulgaria",
114: "Burkina Faso",
115: "Burundi",
116: "Cambodia",
117: "Cameroon",
118: "Cape Verde",
119: "Centrl African Repub",
120: "Chad",
121: "Comoros",
122: "Congo",
123: "Cote dlvoire",
124: "Croatia",
125: "Cyprus",
126: "Czech Republic",
127: "Denmark",
128: "Djibouti",
129: "Dominica",
130: "Egypt",
131: "Eritrea",
132: "Estonia",
133: "Ethiopia",
134: "Fiji",
135: "Finland",
136: "Gabon",
137: "Gambia",
138: "Georgia",
139: "Grenada",
140: "Hungary",
141: "Iceland",
142: "Japan",
143: "Kazakhatan",
144: "Kenya",
145: "Kyrqyzstan",
146: "Latvia",
147: "Lesotho",
148: "Libyn Arab Jamahirya",
149: "Liechtenstein",
150: "Lithuania",
151: "Luxembourg",
152: "Madagascar",
153: "Malawi",
154: "Maldives",
155: "Mali",
156: "Malta",
157: "Marshall Islands",
158: "Mauritania",
159: "Mauritius",
160: "Micronesia",
161: "Moldova",
162: "Monaco",
163: "Mongolia",
164: "Morocco",
165: "Mozambique",
166: "Myanmar",
167: "Namibia",
168: "Nepal",
169: "New Zealand",
170: "Norway",
171: "Oman",
172: "Palau",
173: "Papua New Guinea",
174: "Paraguay",
175: "Qatar",
176: "Rwanda",
177: "Saint Lucia",
178: "St Vincnt/Grenadines",
179: "Samoa",
180: "San Marino",
181: "Sao Tomo & Principe",
182: "Saudi Arabia",
183: "Senegal",
184: "Seychelles",
185: "Sierra Leone",
186: "Singapore",
187: "Slovakia",
188: "Slovenia",
189: "Solomon Islands",
190: "Somalia",
191: "South Africa",
192: "Sri Lanka",
193: "Sudan",
194: "Suriname",
195: "Swaziland",
196: "Sweden",
197: "Switzerland",
198: "Tajikistan",
199: "Tanzania",
200: "Tunisia",
201: "Turkey",
202: "Turkmenistan",
203: "Uganda",
204: "Ukraine",
205: "United Arab Emirates",
206: "Uruguay",
207: "Uzbekistan",
208: "Vanuatu",
209: "Zambia",
210: "Zimbabwe",
211: "United States"
}

district = {
    0: "Maine",
1: "Massachusetts",
2: "New Hampshire",
3: "Rhode Island",
4: "Puerto Rico",
5: "Connecticut",
6: "New York, Northern",
7: "New York, Eastern",
8: "New York, Southern",
9: "New York, Western",
10: "Vermont",
11: "Delaware",
12: "New Jersey",
13: "Pennsylvania, Eastern",
14: "Pennsylvania, Middle",
15: "Pennsylvania, Western",
16: "Maryland",
17: "North Carolina, Eastern",
18: "North Carolina, Middle",
19: "North Carolina, Western",
20: "South Carolina",
22: "Virginia, Eastern",
23: "Virginia, Western",
24: "West Virginia, Northern",
25: "West Virginia, Southern",
26: "Alabama, Northern",
27: "Alabama, Middle",
28: "Alabama, Southern",
29: "Florida, Northern",
30: "Florida, Middle",
31: "Florida, Southern",
32: "Georgia, Northern",
33: "Georgia, Middle",
34: "Georgia, Southern",
35: "Louisiana, Eastern",
36: "Louisiana, Western",
37: "Mississippi, Northern",
38: "Mississippi, Southern",
39: "Texas, Northern",
40: "Texas, Eastern",
41: "Texas, Southern",
42: "Texas, Western",
43: "Kentucky, Eastern",
44: "Kentucky, Western",
45: "Michigan, Eastern",
46: "Michigan, Western",
47: "Ohio, Northern",
48: "Ohio, Southern",
49: "Tennessee, Eastern",
50: "Tennessee, Middle",
51: "Tennessee, Western",
52: "Illinois, Northern",
53: "Illinois, Central",
54: "Illinois, Southern",
55: "Indiana, Northern",
56: "Indiana, Southern",
57: "Wisconsin, Eastern",
58: "Wisconsin, Western",
60: "Arkansas, Eastern",
61: "Arkansas, Western",
62: "Iowa, Northern",
63: "Iowa, Southern",
64: "Minnesota",
65: "Missouri, Eastern",
66: "Missouri, Western",
67: "Nebraska",
68: "North Dakota",
69: "South Dakota",
70: "Arizona",
71: "California, Northern",
72: "California, Eastern",
73: "California, Central",
74: "California, Southern",
75: "Hawaii",
76: "Idaho",
77: "Montana",
78: "Nevada",
79: "Oregon",
80: "Washington, Eastern",
81: "Washington, Western",
82: "Colorado",
83: "Kansas",
84: "New Mexico",
85: "Oklahoma, Northern",
86: "Oklahoma, Eastern",
87: "Oklahoma, Western",
88: "Utah",
89: "Wyoming",
90: "District of Columbia",
91: "Virgin Islands",
93: "Guam",
94: "Mariana Islands, Northern",
95: "Alaska",
96: "Louisiana, Middle"
}

edu = {
    0: 'None',
    1: 'First Grade',
    2: 'Second Grade',
    3: 'Third Grade',
    4: 'Fourth Grade',
    5: 'Fifth Grade',
    6: 'Sixth Grade',
    7: 'Seventh Grade',
    8: 'Eigth Grade',
    9: 'Ninth Grade',
    10: 'Tenth Grade',
    11: 'Eleventh Grade',
    12: 'High School Graduate',
    13: 'College Freshman',
    14: 'College Sophomore',
    15: 'College Junior',
    16: 'College Graduate',
    21: 'General Education Diploma',
    22: 'Trade or vocational degree',
    23: 'Associate degree',
    24: 'Graduate degree',
    31: 'Some elementary school',
    32: 'Some high school',
    33: 'Some trade or vocational school',
    34: 'Some college',
    35: 'Some graduate school',
    36: 'Military training',
    99: 'Other'
}

gender = {
    0 : 'Male',
    1 : 'Female',
}

marriage = {
    1: "Single",
2: "Married",
3: "Cohabitating",
4: "Divorced",
5: "Widowed",
6: "Separated"
}

offense = {
1: "Murder",
2: "Manslaughter",
3: "Kidnapping/Hostage",
4: "Sexual Abuse",
5: "Assault",
6: "Bank Robbery",
7: "Other Robbery",
8: "Extortion",
9: "Arson",
10: "Drugs: Trafficking",
11: "Drugs: Communication Facilities",
12: "Drugs: Simple Possession",
13: "Firearms: Use",
14: "Firearms: Possession, Trafficking",
15: "Burglary/ Breaking and Entering",
16: "Auto Theft",
17: "Larceny",
18: "Fraud",
19: "Embezzlement",
20: "Forgery/ Counterfeiting",
21: "Bribery",
22: "Tax Offenses10",
23: "Money Laundering",
24: "Racketeering",
25: "Gambling/ Lottery",
26: "Civil Rights Offenses",
27: "Immigration",
28: "Pornography/ Prostitution",
29: "Offenses in Prisons",
30: "Administration of Justice - Related",
31: "Environmental, Game, Fish, and Wildlife Offenses",
32: "National Defense Offenses",
33: "Antitrust Violations",
34: "Food and Drug Offenses",
35: "Traffic Violations",
36: "Other Violent Offenses",
37: "Other Drug Offenses",
38: "Other Firearms Offenses",
39: "Other Property Offenses",
40: "Other Environmental Offenses",
41: "Other Miscellaneous Offenses"
}

race = {
    1: "White/Caucasian",
2: "Black",
3: "American Indian or Alaskan Native",
4: "Asian or Pacific Islander",
7: "Other",
9: "Other"
}

attr = {
    "Armed Career Criminal Status": accs,
    "Career Offender Status": cos,
    "Citizenship": citz,
    "District": district,
    'Education': edu,
    'Gender': gender,
    'Marital Status': marriage,
    'Offense': offense,
    'Race': race
}

months = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}

def readable_dob(string_val):
    string_val += ' '
    if string_val[-5:-3] == '19':
        month = months[int(string_val[-7:-5])]
        return month + ' ' + string_val[-9:-7] + ', ' + string_val[-5:-1]
    else:
        month = months[int(string_val[-5:-3])]
        return month + ' ' + string_val[--3:-1] + ', ' + string_val[-9:-5]


def translate_int_to_string(name, int_val):
    if name == 'Date of Birth':
        return readable_dob(str(int_val))
    if name in attr:
        if int_val in attr[name]:
            return attr[name][int_val]
    return 'Other'    
    